### ISSUE TITLE
Hi Sam!. I found the solution to the problem. Hope this can help you!.

### ISSUE THREAD

**Issue by Pablo-MC** [Nytra/MaximizedTerminal#1]
Hi Sam!, how are you?. When installing VSC and wanting to use the integrated terminal in full screen, I ran into the same problem as you. You have made a great contribution!. But, my solution to use the default keyboard shortcut that VSC uses to open terminal but in full screen was as follows:

. Inside my **_keybindings.json_** file I put the following implementation:

`{
        "key": "ctrl+oem_3",
        "command": "workbench.action.toggleMaximizedPanel",
        "when": "!terminalFocus"
 }`

or

`{
        "key": "ctrl+j",
        "command": "workbench.action.toggleMaximizedPanel",
        "when": "!terminalFocus"
 }`

I hope the code works for you. Greetings from Argentina!. 

> Pablo

**Comment by Nytra** [comment]
Great, thanks!

I will try this out for myself, and then I plan to implement it in the next version of the extension :)
