### ISSUE TITLE
Automatically closes when I try top toggle terminal with shortcut

### ISSUE THREAD

**Issue by ChristopherHaws** [Nytra/MaximizedTerminal#13]
Hey there! I've been looking for an extension just like yours! I tried to install it today but ran into an issue where the terminal is maximizing for a split second before closing instantly. I made sure to unbind the default shortcut for `` ctrl+` ``. I even tried in an empty vscode profile with no settings or extensions and the issue still happened.

I am using VSCode Insiders.

**Comment by Nytra** [comment]
Fixed in new release https://github.com/Nytra/MaximizedTerminal/releases/tag/2.1.3

(Update should also be detected in your vscode application)
