### ISSUE TITLE
Requires multiple triggers to reach full screen

### ISSUE THREAD

**Issue by JackCA** [Nytra/MaximizedTerminal#3]
I really love this extension but I've noticed that within the last month or two, the behavior of maximizing has changed.

When triggered maximize via `ctrl+;`, it now seems to alternate between just showing the terminal like (```ctrl+` ```) and actually maximizing it.

**Comment by Nytra** [comment]
Fixed. Thanks for letting me know about this problem 👍

**Comment by JackCA** [comment]
I'm not certain, but originally I thought that if you:

1. Have the terminal window visible, but not maximized
2. Maximize the terminal
3. unmaximize the terminal
4. it would return to state of step 1

I think that's how it used to be for this extension (which I think is the preferred flow). Currently, in step 4, you won't see the terminal at all.

Is that correct?

**Comment by Nytra** [comment]
By default, pressing ctrl+' will try to toggle between a maximized terminal and a closed panel. Alternatively, you can enable the other keybinding in settings (Settings->Extensions->MaximizeTerminal: "Use Alternative Keybinding"), which will allow ctrl+; to have this behaviour, while giving ctrl+' the job of toggling between a minimized terminal and closed panel.

You seem to be requesting a key to toggle between maximized terminal and minimized terminal. I could definitely implement something like this in a future update. Although you would probably have to manually click the close terminal button in this case to close it.

In the meantime, you could try the alternate keybinding option.

**Comment by JackCA** [comment]
@Nytra thanks for the tip! I'll try that out
