### ISSUE TITLE
Keybind and command refuse to work

### ISSUE THREAD

**Issue by cptSwing** [Nytra/MaximizedTerminal#5]
After a recent VSC update (v. 1.53.2) this extension seems to have quit working? While both the keyboard shortcuts as well as the commands to be run from commandline are still existant, nothing happens when I use them. I am running on a Windows machine and using WSL Ubuntu if that makes any difference.

EDIT: Actually, toggling OUT of the terminal seems to work, I just can't toggle back IN

Cheers!

**Comment by Nytra** [comment]
Just pushed version 2.1.1 of the extension, which should fix problems for latest release v1.55.2 of VSCode.
